name: CI
on: [push, pull_request]
#  schedule:
#    - cron: '0 0-23/4 * * *'
jobs:
  webos:
    name: WebOS
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stephank/docker-lg-webos-ndk
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: webos
          max-size: 1G
      - name: Configure
        run: ./configure --host=webos --enable-release
      - name: Build
        run: make -j$(nproc) ipk
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scummvm-ipk
          path: org.scummvm_*.ipk

